// eslint.config.js
module.exports = [
  {
    files: ["proto/js/main.js"], // Only lint main.js
    languageOptions: {
      ecmaVersion: 12,
      sourceType: "script",
      globals: {
        "snowStorm": "readonly",
        "document": "readonly",
        "window": "readonly",
        "navigator": "readonly",
        "clearInterval": "readonly",
        "setInterval": "readonly",
        "setTimeout": "readonly",
        "clearTimeout": "readonly", // Added this
        "parseInt": "readonly",
        "Math": "readonly",
        "console": "readonly",
        "module": "readonly",
        "require": "readonly",
        "__dirname": "readonly",
        "process": "readonly",
        "exports": "readonly",
        "define": "readonly",
        "describe": "readonly",
        "it": "readonly",
        "expect": "readonly",
        "beforeEach": "readonly",
        "afterEach": "readonly",
        "before": "readonly",
        "after": "readonly",
        "xdescribe": "readonly",
        "xit": "readonly",
        "fdescribe": "readonly",
        "fit": "readonly",
        "spyOn": "readonly",
        "jasmine": "readonly",
        "getComputedStyle": "readonly",
        "IntersectionObserver": "readonly",
        "customElements": "readonly",
        "HTMLElement": "readonly",
        "CustomEvent": "readonly",
        "Image": "readonly",
        "location": "readonly",
        "localStorage": "readonly",
        "sessionStorage": "readonly",
        "alert": "readonly",
        "confirm": "readonly",
        "prompt": "readonly",
        "fetch": "readonly",
        "Headers": "readonly",
        "Request": "readonly",
        "Response": "readonly",
        "URL": "readonly",
        "URLSearchParams": "readonly",
        "XMLHttpRequest": "readonly",
        "FormData": "readonly",
        "FileReader": "readonly",
        "File": "readonly",
        "Blob": "readonly",
        "ArrayBuffer": "readonly",
        "DataView": "readonly",
        "Promise": "readonly",
        "Map": "readonly",
        "Set": "readonly",
        "WeakMap": "readonly",
        "WeakSet": "readonly",
        "Symbol": "readonly",
        "Reflect": "readonly",
        "Proxy": "readonly",
        "Intl": "readonly",
        "WebAssembly": "readonly",
        "SharedArrayBuffer": "readonly",
        "Atomics": "readonly",
        "JSON": "readonly",
        "isNaN": "readonly",
        "isFinite": "readonly",
        "parseFloat": "readonly",
        "encodeURI": "readonly",
        "decodeURI": "readonly",
        "encodeURIComponent": "readonly",
        "decodeURIComponent": "readonly",
        "escape": "readonly",
        "unescape": "readonly",
        "Date": "readonly"
      }
    },
    rules: {
      "no-unused-vars": "warn",
      "no-undef": "warn"
    }
  }
];